### ISSUE TITLE
Patch is failing for 4.17.0.1

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-java-driver-matrix#50]
```
Driver version: 4.17.0.1
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-6.0/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/main.py", line 31, in main
    scylla_version=scylla_version).run()
                                   ^^^^^
  File "/jenkins/workspace/scylla-6.0/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/run.py", line 122, in run
    self._apply_patch_files()
  File "/jenkins/workspace/scylla-6.0/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/run.py", line 109, in _apply_patch_files
    self._run_command_in_shell(f"git apply -v --check {file_path}")
  File "/jenkins/workspace/scylla-6.0/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/run.py", line 98, in _run_command_in_shell
    assert status_code == 0, stderr
           ^^^^^^^^^^^^^^^^
AssertionError: Checking patch integration-tests/src/test/java/com/datastax/oss/driver/core/PeersV2NodeRefreshIT.java...
error: while searching for:
    }
  }

  @Test
  public void should_successfully_send_peers_v2_node_refresh_query()
      throws InterruptedException, ExecutionException {
    CqlSession session =
        CqlSession.builder().addContactPoint(cluster.node(1).inetSocketAddress()).build();
    Node node = findNonControlNode(session);
    ((InternalDriverContext) session.getContext())
        .getMetadataManager()

error: patch failed: integration-tests/src/test/java/com/datastax/oss/driver/core/PeersV2NodeRefreshIT.java:53
error: integration-tests/src/test/java/com/datastax/oss/driver/core/PeersV2NodeRefreshIT.java: patch does not apply
Checking patch test-infra/src/main/java/com/datastax/oss/driver/api/testinfra/ccm/BaseCcmRule.java...
Checking patch test-infra/src/main/java/com/datastax/oss/driver/api/testinfra/ccm/CcmBridge.java...
Checking patch test-infra/src/main/java/com/datastax/oss/driver/api/testinfra/ccm/CustomCcmRule.java...
```

**Comment by Bouncheck** [comment]
Resolved by #66 .
Most recent successful run for this version: https://jenkins.scylladb.com/job/scylla-master/job/driver-tests/job/java-driver-matrix-test/1548/
