### ISSUE TITLE
patch is failing for datastax version 4.18.1

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla-java-driver-matrix#51]
```
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-6.0/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/main.py", line 31, in main
    scylla_version=scylla_version).run()
                                   ^^^^^
  File "/jenkins/workspace/scylla-6.0/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/run.py", line 122, in run
    self._apply_patch_files()
  File "/jenkins/workspace/scylla-6.0/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/run.py", line 109, in _apply_patch_files
    self._run_command_in_shell(f"git apply -v --check {file_path}")
  File "/jenkins/workspace/scylla-6.0/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/run.py", line 98, in _run_command_in_shell
    assert status_code == 0, stderr
           ^^^^^^^^^^^^^^^^
AssertionError: Checking patch integration-tests/src/test/java/com/datastax/oss/driver/core/metadata/NodeMetadataIT.java...
Checking patch test-infra/revapi.json...
Checking patch test-infra/src/main/java/com/datastax/oss/driver/api/testinfra/ccm/BaseCcmRule.java...
Checking patch test-infra/src/main/java/com/datastax/oss/driver/api/testinfra/ccm/CcmBridge.java...
error: while searching for:
      execute(
          "create",
          CLUSTER_NAME,
          "-i",
          ipPrefix,
          "-n",
          Arrays.stream(nodes).mapToObj(n -> "" + n).collect(Collectors.joining(":")),
          createOptions.stream().collect(Collectors.joining(" ")));

      for (Map.Entry<String, Object> conf : cassandraConfiguration.entrySet()) {
        execute("updateconf", String.format("%s:%s", conf.getKey(), conf.getValue()));
      }
      if (getCassandraVersion().compareTo(Version.V2_2_0) >= 0) {
        execute("updateconf", "enable_user_defined_functions:true");
      }
      if (DSE_ENABLEMENT) {
        for (Map.Entry<String, Object> conf : dseConfiguration.entrySet()) {
          execute("updatedseconf", String.format("%s:%s", conf.getKey(), conf.getValue()));

error: patch failed: test-infra/src/main/java/com/datastax/oss/driver/api/testinfra/ccm/CcmBridge.java:230
error: test-infra/src/main/java/com/datastax/oss/driver/api/testinfra/ccm/CcmBridge.java: patch does not apply
Checking patch test-infra/src/main/java/com/datastax/oss/driver/api/testinfra/ccm/CustomCcmRule.java...
Checking patch test-infra/src/main/java/com/datastax/oss/driver/api/testinfra/ccm/DefaultCcmBridgeBuilderCustomizer.java...
```

**Comment by fruch** [comment]
> Are we trying the same patch we have for 4.17.0.0?

not sure I follow the question

we have different set of patch for the different repos

**Comment by roydahan** [comment]
But who created the patch for 4.18.0.1?

**Comment by fruch** [comment]
> But who created the patch for 4.18.0.1?

No one, I don't think there is such a version yet

**Comment by Bouncheck** [comment]
Resolved by #63 .
The patch applies and the tests are run ([example run](https://jenkins.scylladb.com/job/scylla-master/job/driver-tests/job/java-driver-matrix-test/1547)).
There is a separate issue about report not being generated (#71)
