### ISSUE TITLE
Fix patches on master

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-java-driver-matrix#57]
[Last run](https://jenkins.scylladb.com/view/master/job/scylla-master/job/driver-tests/job/java-driver-matrix-test/1486/consoleFull) on master failed on pathing:
```
Traceback (most recent call last):
19:21:22    File "/jenkins/workspace/scylla-master/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/main.py", line 31, in main
19:21:22      report = runner.run()
19:21:22               ^^^^^^^^^^^^
19:21:22    File "/jenkins/workspace/scylla-master/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/run.py", line 139, in run
19:21:22      self._apply_patch_files()
19:21:22    File "/jenkins/workspace/scylla-master/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/run.py", line 107, in _apply_patch_files
19:21:22      for file_path in self.version_folder.iterdir():
19:21:22                       ^^^^^^^^^^^^^^^^^^^
19:21:22    File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
19:21:22      val = self.func(instance)
19:21:22            ^^^^^^^^^^^^^^^^^^^
19:21:22    File "/jenkins/workspace/scylla-master/driver-tests/java-driver-matrix-test/scylla-java-driver-matrix/run.py", line 61, in version_folder
19:21:22      target_version = Version(self.version)
19:21:22                       ^^^^^^^^^^^^^^^^^^^^^
19:21:22    File "/usr/local/lib/python3.11/site-packages/packaging/version.py", line 198, in __init__
19:21:22      raise InvalidVersion(f"Invalid version: '{version}'")
19:21:22  packaging.version.InvalidVersion: Invalid version: '4.1.0_fixes'
```

**Comment by dkropachev** [comment]
Done
